//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adress
    {
        public int areaid { get; set; }
        public string area { get; set; }
        public Nullable<int> cityID { get; set; }
    
        public virtual city city { get; set; }
    }
}
