//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Rid { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Qualification { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    }
}
