//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class school
    {
        public int Sid { get; set; }
        public string Studentname { get; set; }
        public string location { get; set; }
        public string mobile { get; set; }
        public string Gender { get; set; }
    }
}
