//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int stateid { get; set; }
        public string statename { get; set; }
        public string cityname { get; set; }
        public string area { get; set; }
    }
}
