//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_facaulty
    {
        public int FID { get; set; }
        public string FACULTYNAME { get; set; }
        public string SUB { get; set; }
        public string GENDER { get; set; }
        public string EMAIL { get; set; }
    }
}
